#!/bin/sh

if ! command -v java >/dev/null 2>&1; then
    echo "Java is not installed, please install java version 21"
    exit 1
fi
draw_line() {
    i=0; while [ $i -lt "$(("$2"+2))" ]; do
        printf "%s" "$1"
        i=$((i+1))
    done
}
draw_addr() {
    tb="─" lr="│" tl="╭" tr="╮" bl="╰" br="╯"
    len="${#1}"
    printf "%s" "$tl"; draw_line "$tb" "$len"; echo "$tr"
    printf "%s" "$lr"; printf " %s " "$1"; echo "$lr"
    printf "%s" "$bl"; draw_line "$tb" "$len"; echo "$br"
}

name="mcsv" # Container name
ztkey="$HOME/.mcsv.ztkey"
ztnet="$HOME/.mcsv.ztnet"
manual_zt() {
    if [ ! -f "$ztkey" ]; then
        zerotier-idtool generate > "$ztkey"
    fi
    zidpublic="$(sed 's/:/\n/3' "$ztkey" | head -n1)"
    zidsecret="$(cat "$ztkey")"
    killall zerotier-one 2>/dev/null
    printf "%s" "$zidpublic" > /var/lib/zerotier-one/identity.secret
    printf "%s" "$zidsecret" > /var/lib/zerotier-one/identity.public
    zerotier-one -d
    zerotier-cli join "$znetid"
    while [ -z "$(zerotier-cli listnetworks | grep "$znetid" | awk '{print $9}' | cut -d"/" -f1)" ]; do :; echo "getting ZeroTier ip..."; sleep 1; done
    ztip="$(zerotier-cli listnetworks | grep "$znetid" | awk '{print $9}' | cut -d"/" -f1)"
}
docker_zt() {
    if [ ! -f "$ztkey" ]; then
        docker run -d --name getztkey --rm --cap-add NET_ADMIN --device /dev/net/tun zerotier/zerotier:latest
        docker exec getztkey zerotier-idtool generate > "$ztkey"
        docker stop getztkey
    fi
    zidpublic="$(sed 's/:/\n/3' "$ztkey" | head -n1)"
    zidsecret="$(cat "$ztkey")"
    docker stop "$name" 2>/dev/null
    docker run \
    -d \
    --rm \
    --net=host \
    --name "$name" \
    --env ZEROTIER_IDENTITY_PUBLIC="$zidpublic" \
    --env ZEROTIER_IDENTITY_SECRET="$zidsecret" \
    --cap-add NET_ADMIN \
    --device /dev/net/tun \
    zerotier/zerotier:latest \
    "$znetid"
    while [ -z "$(docker exec "$name" zerotier-cli listnetworks | grep "$znetid" | awk '{print $9}' | cut -d"/" -f1)" ]; do :; echo "getting ZeroTier ip..."; sleep 1; done
    ztip="$(docker exec "$name" zerotier-cli listnetworks | grep "$znetid" | awk '{print $9}' | cut -d"/" -f1)"
}
setup_and_run_zt() {
    if [ ! -f "$ztnet" ] || [ -z "$(cat "$ztnet" )" ]; then
        printf "Please enter ZeroTier Network ID: "
        read -r id
        echo "$id" > "$ztnet"
    fi
    znetid="$(cat "$ztnet")"
    if command -v zerotier-one >/dev/null 2>&1; then
        manual_zt
    elif command -v docker >/dev/null 2>&1; then
        docker_zt
    else
        echo "Both Docker and ZeroTier are not installed!"
        echo "Please install docker"
        echo "OR"
        echo "Install and configure Zerotier manually"
        echo "Then re-run this script with z flag"
        exit 1
    fi

    draw_addr "ZeroTier ip: $ztip"
}

while getopts 'zr' opt; do
    case "$opt" in
        z) setup_and_run_zt ;;
        r) rmworld=true ;;
        *) echo "Invalid option!" ;;
    esac
done
shift $((OPTIND-1))

[ -z "$1" ] && echo "Please specify Server version (the name of the folder contain server jar file)" && exit 1

pwd=$PWD; cd "$1" || exit 1

[ "$rmworld" = true ] && rm -rfv ops.json permissions.yml usercache.json world*
sudo update-java-alternatives --set java-1.21.0-openjdk-amd64 || java --version
java -Xmx4096M -Xms4096M -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar ./*.jar nogui | \
while read -r line; do
    set -- $line
    case "$5" in
        *.e4mc.link) draw_addr "e4mc address: $5" ;;
        *) echo "$line" ;;
    esac
done

cd "$pwd" || exit 1
